// ReWearHub — 50 Real Indian Fashion Products
export const mockProducts = [
  // ── ETHNIC MEN ──────────────────────────────────────────────
  {
    id: 1, name: 'Royal Blue Sherwani Set', category: 'ethnic', gender: 'men',
    occasion: 'wedding', color: 'Royal Blue', fabric: 'Raw Silk',
    size: ['S','M','L','XL','XXL'], pricePerDay: 699, deposit: 2500,
    rating: 4.9, reviewCount: 312, totalRentals: 845, available: true,
    trending: true, celebrity: false,
    image: 'https://images.unsplash.com/photo-1610030469983-98e550d6193c?w=500&q=80',
    description: 'Exquisite royal blue sherwani crafted from premium raw silk with intricate gold zardozi embroidery on the chest and cuffs. Comes with matching churidar, dupatta, and embroidered mojris. Perfect for groom or groomsmen.',
    features: ['Zardozi Embroidery','Churidar & Dupatta Included','Dry Cleaned','European Lining'],
    brand: 'Manyavar Elite', tags: ['trending','bestseller'], badge: '🔥 Most Rented', discount: 30,
  },
  {
    id: 2, name: 'Ivory Bandhgala Suit', category: 'ethnic', gender: 'men',
    occasion: 'wedding', color: 'Ivory', fabric: 'Silk Blend',
    size: ['S','M','L','XL'], pricePerDay: 549, deposit: 2000,
    rating: 4.8, reviewCount: 198, totalRentals: 634, available: true,
    trending: true, celebrity: true,
    image: 'https://images.unsplash.com/photo-1621784563330-caee0b138a00?w=500&q=80',
    description: 'Shah Rukh Khan-inspired ivory bandhgala suit with subtle gold threadwork on the collar and buttons. Timeless piece blending traditional silhouette with modern tailoring — perfect for cocktail nights or sangeet ceremonies.',
    features: ['Mandarin Collar','Gold Thread Buttons','Slim Fit','SRK Inspired'],
    brand: 'Rohit Bal Studio', tags: ['celebrity','trending'], badge: '⭐ Celebrity Pick', discount: 25,
  },
  {
    id: 3, name: 'Navy Blue Nehru Jacket Set', category: 'ethnic', gender: 'men',
    occasion: 'festival', color: 'Navy Blue', fabric: 'Brocade',
    size: ['S','M','L','XL','XXL'], pricePerDay: 349, deposit: 1200,
    rating: 4.6, reviewCount: 145, totalRentals: 389, available: true,
    trending: false, celebrity: false,
    image: 'https://images.unsplash.com/photo-1583743814966-8936f5b7be1a?w=500&q=80',
    description: 'Elegant navy blue Nehru jacket in brocade fabric with matching kurta and off-white churidar. The structured silhouette and self-woven floral pattern make it ideal for Diwali parties, Navratri, or reception nights.',
    features: ['Brocade Weave','Matching Kurta','Stand Collar','Dry Cleaned'],
    brand: 'Fabindia Premium', tags: [], badge: null, discount: 20,
  },
  {
    id: 4, name: 'Maroon Velvet Sherwani', category: 'ethnic', gender: 'men',
    occasion: 'wedding', color: 'Maroon', fabric: 'Velvet',
    size: ['M','L','XL'], pricePerDay: 799, deposit: 3000,
    rating: 4.9, reviewCount: 267, totalRentals: 523, available: true,
    trending: true, celebrity: false,
    image: 'https://images.unsplash.com/photo-1596902852634-da8d3cc1988c?w=500&q=80',
    description: 'Luxurious maroon velvet sherwani with gold antique embroidery throughout the body. This show-stopping piece comes with a layered cape-style dupatta and churidar — designed for grooms who want to make a statement.',
    features: ['Heavy Velvet','Cape Dupatta','Gold Antique Embroidery','Festive Packaging'],
    brand: 'Sabyasachi x ReWear', tags: ['trending','bestseller'], badge: '💎 Premium', discount: 35,
  },
  {
    id: 5, name: 'Off-White Linen Kurta Pyjama', category: 'casual', gender: 'men',
    occasion: 'casual', color: 'Off White', fabric: 'Linen',
    size: ['S','M','L','XL','XXL'], pricePerDay: 149, deposit: 500,
    rating: 4.5, reviewCount: 89, totalRentals: 234, available: true,
    trending: false, celebrity: false,
    image: 'https://images.unsplash.com/photo-1539109136881-3be0616acf4b?w=500&q=80',
    description: 'Breathable off-white linen kurta with matching pyjama, perfect for a relaxed yet stylish look. Subtle pintuck detailing on the kurta front adds elegance without being overdressed.',
    features: ['100% Linen','Pintuck Detail','Relaxed Fit','Machine Washable'],
    brand: 'Fabindia', tags: [], badge: null, discount: 15,
  },
  {
    id: 6, name: 'Black Pathaan Action Jacket', category: 'formal', gender: 'men',
    occasion: 'party', color: 'Black', fabric: 'Neoprene',
    size: ['M','L','XL'], pricePerDay: 799, deposit: 2500,
    rating: 4.9, reviewCount: 445, totalRentals: 1023, available: true,
    trending: true, celebrity: true,
    image: 'https://images.unsplash.com/photo-1617196034183-421b4040ed20?w=500&q=80',
    description: 'Exact replica of the iconic black structured jacket worn by Shah Rukh Khan in Pathaan. Features signature angular cuts, subtle metallic sheen, and fitted silhouette. This look defines the modern Bollywood action hero.',
    features: ['SRK Pathaan Replica','Structured Shoulder','Metallic Sheen','Matching Belt'],
    brand: 'ReWear Celebrity', tags: ['celebrity','trending','bestseller'], badge: '⭐ #1 Most Rented', discount: 40,
  },
  {
    id: 7, name: 'Peach Printed Kurta Set', category: 'ethnic', gender: 'men',
    occasion: 'festival', color: 'Peach', fabric: 'Cotton',
    size: ['S','M','L','XL'], pricePerDay: 199, deposit: 700,
    rating: 4.4, reviewCount: 56, totalRentals: 145, available: true,
    trending: false, celebrity: false,
    image: 'https://images.unsplash.com/photo-1555069519-127aadecd7f9?w=500&q=80',
    description: 'Soft peach cotton kurta with block-printed motifs and a matching pajama. Ideal for Holi, Diwali, or relaxed family functions. Light, breathable, and effortlessly stylish.',
    features: ['Block Print','Pure Cotton','Festive Colors','Comfortable Fit'],
    brand: 'Fabindia', tags: [], badge: null, discount: 20,
  },
  {
    id: 8, name: 'Emerald Green Silk Sherwani', category: 'ethnic', gender: 'men',
    occasion: 'wedding', color: 'Emerald Green', fabric: 'Pure Silk',
    size: ['S','M','L','XL'], pricePerDay: 649, deposit: 2200,
    rating: 4.7, reviewCount: 178, totalRentals: 412, available: true,
    trending: true, celebrity: false,
    image: 'https://images.unsplash.com/photo-1600091166971-7f9faad6c498?w=500&q=80',
    description: 'Rich emerald green pure silk sherwani with resham thread embroidery and stone work on the yoke. The deep jewel tone is perfect for festive functions, includes matching silk stole.',
    features: ['Pure Silk','Resham Embroidery','Stone Work','Silk Stole Included'],
    brand: 'Manyavar', tags: ['trending'], badge: null, discount: 28,
  },
  // ── ETHNIC WOMEN ─────────────────────────────────────────
  {
    id: 9, name: 'Crimson Bridal Lehenga', category: 'ethnic', gender: 'women',
    occasion: 'wedding', color: 'Crimson Red', fabric: 'Georgette',
    size: ['XS','S','M','L','XL'], pricePerDay: 1299, deposit: 5000,
    rating: 4.9, reviewCount: 534, totalRentals: 1234, available: true,
    trending: true, celebrity: false,
    image: 'https://images.unsplash.com/photo-1583391733956-3750e0ff4e8b?w=500&q=80',
    description: 'A breathtaking crimson bridal lehenga in pure georgette with intricate hand-embroidered zari and mirror work. 5-metre flare skirt, 12 layers of lining, heavily embellished choli, and dupatta with scalloped borders.',
    features: ['5M Flare Skirt','12-Layer Lining','Mirror Work Choli','Dupatta Included','Petticoat Included'],
    brand: 'Sabyasachi x ReWear', tags: ['trending','bestseller'], badge: '👑 Bridal Favourite', discount: 45,
  },
  {
    id: 10, name: 'Rose Gold Anarkali Gown', category: 'ethnic', gender: 'women',
    occasion: 'wedding', color: 'Rose Gold', fabric: 'Net + Satin',
    size: ['XS','S','M','L'], pricePerDay: 699, deposit: 2500,
    rating: 4.8, reviewCount: 398, totalRentals: 892, available: true,
    trending: true, celebrity: false,
    image: 'https://images.unsplash.com/photo-1595777457583-95e059d581b8?w=500&q=80',
    description: 'Floor-sweeping rose gold anarkali in net over satin with sequin and thread embroidery across the bodice and sleeves. A-line silhouette — universally flattering for reception nights and sangeet parties.',
    features: ['Floor Length','Sequin Bodice','Full Sleeves','Lining Included'],
    brand: 'Anju Modi', tags: ['trending'], badge: '✨ Most Loved', discount: 32,
  },
  {
    id: 11, name: 'Electric Blue Chiffon Saree', category: 'ethnic', gender: 'women',
    occasion: 'party', color: 'Electric Blue', fabric: 'Chiffon',
    size: ['Free Size'], pricePerDay: 349, deposit: 1200,
    rating: 4.7, reviewCount: 234, totalRentals: 567, available: true,
    trending: false, celebrity: false,
    image: 'https://images.unsplash.com/photo-1617627143750-d86bc21e42bb?w=500&q=80',
    description: 'Stunning electric blue chiffon saree with silver sequin border and matching embroidered blouse. Lightweight chiffon drapes beautifully — includes pre-stitched petticoat and blouse.',
    features: ['Pre-Stitched Petticoat','Blouse Included','Sequin Border','Lightweight Chiffon'],
    brand: 'Sunayna Raina', tags: [], badge: null, discount: 22,
  },
  {
    id: 12, name: 'Pastel Pink Sharara Set', category: 'ethnic', gender: 'women',
    occasion: 'festival', color: 'Pastel Pink', fabric: 'Organza',
    size: ['XS','S','M','L','XL'], pricePerDay: 499, deposit: 1800,
    rating: 4.8, reviewCount: 289, totalRentals: 678, available: true,
    trending: true, celebrity: false,
    image: 'https://images.unsplash.com/photo-1600080972464-8e5f35f63d08?w=500&q=80',
    description: 'Dreamy pastel pink sharara set in flowy organza with floral prints and dori embroidery. Wide-legged sharara trousers create an elegant silhouette, matched with a cropped embroidered kurti and matching dupatta.',
    features: ['Organza Fabric','Wide-Leg Sharara','Printed Kurti','Dupatta Included'],
    brand: 'Anita Dongre', tags: ['trending'], badge: '🌸 New Season', discount: 28,
  },
  {
    id: 13, name: 'Mustard Bandhani Saree', category: 'ethnic', gender: 'women',
    occasion: 'festival', color: 'Mustard Yellow', fabric: 'Pure Silk',
    size: ['Free Size'], pricePerDay: 449, deposit: 1500,
    rating: 4.6, reviewCount: 167, totalRentals: 389, available: true,
    trending: false, celebrity: false,
    image: 'https://images.unsplash.com/photo-1617196034099-e63fd4a09e76?w=500&q=80',
    description: 'Vibrant mustard yellow bandhani saree in pure Rajasthani silk with intricate tie-dye patterns and a contrasting red border. Perfect for Navratri, Teej, or any regional festival.',
    features: ['Rajasthani Bandhani','Pure Silk','Red Border','Blouse Material Included'],
    brand: 'Rajasthali', tags: [], badge: null, discount: 18,
  },
  {
    id: 14, name: 'Deep Maroon Kanjeevaram Saree', category: 'ethnic', gender: 'women',
    occasion: 'wedding', color: 'Deep Maroon', fabric: 'Kanjeevaram Silk',
    size: ['Free Size'], pricePerDay: 899, deposit: 3500,
    rating: 4.9, reviewCount: 412, totalRentals: 876, available: true,
    trending: true, celebrity: false,
    image: 'https://images.unsplash.com/photo-1583391733956-3750e0ff4e8b?w=500&q=80',
    description: 'Authentic Kanjeevaram silk saree in deep maroon with real gold zari weaving. The signature temple border and pallu make this a timeless wedding staple. Paired with pre-stitched blouse in matching silk.',
    features: ['Authentic Kanjeevaram','Real Gold Zari','Temple Border','Pre-Stitched Blouse'],
    brand: 'Nalli Silks Heritage', tags: ['trending','bestseller'], badge: '🏆 Heritage Piece', discount: 38,
  },
  {
    id: 15, name: 'Sky Blue Palazzo Suit', category: 'casual', gender: 'women',
    occasion: 'casual', color: 'Sky Blue', fabric: 'Rayon',
    size: ['XS','S','M','L','XL','XXL'], pricePerDay: 199, deposit: 600,
    rating: 4.4, reviewCount: 123, totalRentals: 312, available: true,
    trending: false, celebrity: false,
    image: 'https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?w=500&q=80',
    description: 'Breezy sky blue palazzo suit in soft rayon with floral digital prints. Wide-leg palazzo pants create a boho-chic silhouette that works for casual brunches, family gatherings, or cultural events.',
    features: ['Digital Print','Wide Palazzo','Breathable Rayon','Dupatta Included'],
    brand: 'Global Desi', tags: [], badge: null, discount: 15,
  },
  {
    id: 16, name: 'Forest Green Crepe Salwar Suit', category: 'ethnic', gender: 'women',
    occasion: 'office', color: 'Forest Green', fabric: 'Crepe Silk',
    size: ['S','M','L','XL'], pricePerDay: 299, deposit: 1000,
    rating: 4.5, reviewCount: 89, totalRentals: 234, available: true,
    trending: false, celebrity: false,
    image: 'https://images.unsplash.com/photo-1583143024015-6c029b9d7c7a?w=500&q=80',
    description: 'Professional yet graceful forest green crepe silk salwar kameez with subtle self-embroidery and piped edges. Straight-cut kameez with tapered salwar — perfect for office wear or formal lunches.',
    features: ['Self Embroidery','Straight Cut','Tapered Salwar','Dupatta Included'],
    brand: 'Biba Premium', tags: [], badge: null, discount: 20,
  },
  // ── FORMAL MEN ───────────────────────────────────────────
  {
    id: 17, name: 'Midnight Black Tuxedo', category: 'formal', gender: 'men',
    occasion: 'party', color: 'Black', fabric: 'Wool Blend',
    size: ['S','M','L','XL','XXL'], pricePerDay: 549, deposit: 2000,
    rating: 4.8, reviewCount: 234, totalRentals: 567, available: true,
    trending: true, celebrity: false,
    image: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=500&q=80',
    description: 'Classic black notch-lapel tuxedo in premium wool blend with satin trim. Includes matching trousers with satin stripe, white tuxedo shirt, black bow tie, and pocket square. Professionally dry-cleaned.',
    features: ['Wool Blend','Satin Lapel Trim','Shirt & Bow Tie Included','Pocket Square'],
    brand: 'Raymond Black Label', tags: ['trending'], badge: '🎩 Black Tie Ready', discount: 30,
  },
  {
    id: 18, name: 'Charcoal Grey 3-Piece Suit', category: 'formal', gender: 'men',
    occasion: 'office', color: 'Charcoal Grey', fabric: 'Wool',
    size: ['S','M','L','XL'], pricePerDay: 449, deposit: 1500,
    rating: 4.7, reviewCount: 178, totalRentals: 423, available: true,
    trending: false, celebrity: false,
    image: 'https://images.unsplash.com/photo-1509631179647-0177331693ae?w=500&q=80',
    description: 'Sharp charcoal grey 3-piece suit (jacket, trouser, waistcoat) in pure wool with subtle herringbone texture. Slim fit with peak lapels — ideal for board meetings, corporate events, or power lunches.',
    features: ['Pure Wool','3-Piece Set','Peak Lapels','Slim Fit','Tie Included'],
    brand: 'Louis Philippe Black', tags: [], badge: null, discount: 25,
  },
  {
    id: 19, name: 'Navy Blue Slim Fit Blazer', category: 'semi-formal', gender: 'men',
    occasion: 'party', color: 'Navy Blue', fabric: 'Polyester Blend',
    size: ['S','M','L','XL','XXL'], pricePerDay: 349, deposit: 1200,
    rating: 4.6, reviewCount: 145, totalRentals: 345, available: true,
    trending: false, celebrity: false,
    image: 'https://images.unsplash.com/photo-1514794049506-7b8d23cf3c0d?w=500&q=80',
    description: 'Versatile navy blue slim-fit blazer perfect for smart casual occasions. Pair with chinos for a date night or with formal trousers for an office presentation. Features functional sleeve buttons and flap pockets.',
    features: ['Slim Fit','Functional Buttons','Notch Lapel','Chest Pocket'],
    brand: 'Arrow Metropolitan', tags: [], badge: null, discount: 18,
  },
  {
    id: 20, name: 'Burgundy Velvet Blazer', category: 'semi-formal', gender: 'men',
    occasion: 'party', color: 'Burgundy', fabric: 'Velvet',
    size: ['S','M','L','XL'], pricePerDay: 399, deposit: 1400,
    rating: 4.7, reviewCount: 189, totalRentals: 456, available: true,
    trending: true, celebrity: false,
    image: 'https://images.unsplash.com/photo-1591047139829-d91aecb6caea?w=500&q=80',
    description: 'Rich burgundy velvet blazer with a gold pocket square and satin-lined interior. A statement piece for cocktail evenings, sangeet nights, and festive dinners. Pairs beautifully with black trousers.',
    features: ['Velvet Fabric','Satin Lined','Gold Pocket Square','Statement Piece'],
    brand: 'Jack & Jones Premium', tags: ['trending'], badge: '🔥 Party Favourite', discount: 22,
  },
  {
    id: 21, name: 'White Linen Beach Suit', category: 'casual', gender: 'men',
    occasion: 'casual', color: 'White', fabric: 'Linen',
    size: ['S','M','L','XL','XXL'], pricePerDay: 299, deposit: 1000,
    rating: 4.5, reviewCount: 98, totalRentals: 267, available: true,
    trending: false, celebrity: false,
    image: 'https://images.unsplash.com/photo-1489987707025-afc232f7ea0f?w=500&q=80',
    description: 'Relaxed white linen 2-piece set (shirt + trousers) perfect for beach weddings, resort occasions, or summer brunches. Breathable fabric keeps you cool while looking effortlessly stylish.',
    features: ['100% Linen','2-Piece Set','Relaxed Fit','Breathable'],
    brand: 'H&M Premium', tags: [], badge: null, discount: 15,
  },
  // ── FORMAL WOMEN ─────────────────────────────────────────
  {
    id: 22, name: 'Emerald Satin Evening Gown', category: 'formal', gender: 'women',
    occasion: 'party', color: 'Emerald Green', fabric: 'Satin',
    size: ['XS','S','M','L'], pricePerDay: 699, deposit: 2500,
    rating: 4.8, reviewCount: 312, totalRentals: 734, available: true,
    trending: true, celebrity: false,
    image: 'https://images.unsplash.com/photo-1566479179817-0b61da88e4e4?w=500&q=80',
    description: 'Stunning floor-length emerald green satin evening gown with a plunging V-neckline and side slit. Bias-cut design hugs curves while the satin sheen adds luxurious finish — perfect for award nights and galas.',
    features: ['Floor Length','V-Neckline','Side Slit','Bias Cut','Invisible Zip'],
    brand: 'Masaba Gupta', tags: ['trending'], badge: '✨ Runway Look', discount: 35,
  },
  {
    id: 23, name: 'Black Sequin Cocktail Dress', category: 'formal', gender: 'women',
    occasion: 'party', color: 'Black', fabric: 'Sequin Mesh',
    size: ['XS','S','M','L'], pricePerDay: 549, deposit: 1800,
    rating: 4.7, reviewCount: 245, totalRentals: 589, available: true,
    trending: true, celebrity: false,
    image: 'https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?w=500&q=80',
    description: 'All-over black sequin cocktail dress with a flattering A-line silhouette and knee-length hem. Sequined mesh catches every light beautifully — guaranteed to be the most glamorous look at any cocktail party.',
    features: ['All-Over Sequins','A-Line Silhouette','Knee Length','Back Zip'],
    brand: 'Swapnil Shinde', tags: ['trending'], badge: '🌟 Glam Pick', discount: 28,
  },
  {
    id: 24, name: 'Blush Pink Ballgown', category: 'formal', gender: 'women',
    occasion: 'wedding', color: 'Blush Pink', fabric: 'Organza',
    size: ['XS','S','M','L','XL'], pricePerDay: 799, deposit: 3000,
    rating: 4.9, reviewCount: 389, totalRentals: 823, available: true,
    trending: true, celebrity: false,
    image: 'https://images.unsplash.com/photo-1612840394816-d23a24c0e89c?w=500&q=80',
    description: 'Fairy-tale blush pink organza gown with 3D floral appliques on the bodice and full ballgown skirt. Corset-style top gives a perfect silhouette, while layered organza skirt creates a dreamy voluminous look.',
    features: ['3D Floral Applique','Corset Bodice','Ballgown Skirt','Hoop Frame Included'],
    brand: 'Gaurav Gupta', tags: ['trending','bestseller'], badge: "🌸 Bride's Choice", discount: 42,
  },
  {
    id: 25, name: 'Royal Purple Blazer Dress', category: 'semi-formal', gender: 'women',
    occasion: 'office', color: 'Royal Purple', fabric: 'Crepe',
    size: ['XS','S','M','L','XL'], pricePerDay: 349, deposit: 1200,
    rating: 4.6, reviewCount: 156, totalRentals: 378, available: true,
    trending: false, celebrity: false,
    image: 'https://images.unsplash.com/photo-1604014237800-1c9102c219da?w=500&q=80',
    description: 'Power-dressing at its finest — royal purple crepe blazer dress with structured shoulders and belted waist. Transitions from board meetings to evening events effortlessly. Includes matching belt.',
    features: ['Structured Shoulders','Belted Waist','Power Dressing','Belt Included'],
    brand: 'Forever New', tags: [], badge: null, discount: 20,
  },
  // ── INDO-WESTERN ─────────────────────────────────────────
  {
    id: 26, name: 'Cape Dhoti Pant Set', category: 'ethnic', gender: 'men',
    occasion: 'party', color: 'Indigo', fabric: 'Chanderi',
    size: ['S','M','L','XL'], pricePerDay: 449, deposit: 1500,
    rating: 4.7, reviewCount: 167, totalRentals: 412, available: true,
    trending: true, celebrity: false,
    image: 'https://images.unsplash.com/photo-1561861422-a549073e547a?w=500&q=80',
    description: 'Contemporary Indo-western dhoti pant set in indigo chanderi with a cape-style kurta and printed gold motifs. Unique silhouette marries traditional dhoti draping with modern tailoring — ideal for pre-wedding functions.',
    features: ['Cape Kurta','Dhoti Pants','Chanderi Fabric','Gold Print'],
    brand: 'Tarun Tahiliani', tags: ['trending'], badge: '🎨 Indo-Western', discount: 27,
  },
  {
    id: 27, name: 'Mint Green Peplum Lehenga', category: 'ethnic', gender: 'women',
    occasion: 'party', color: 'Mint Green', fabric: 'Net',
    size: ['XS','S','M','L'], pricePerDay: 599, deposit: 2000,
    rating: 4.8, reviewCount: 278, totalRentals: 634, available: true,
    trending: true, celebrity: false,
    image: 'https://images.unsplash.com/photo-1585771724684-38269d6639fd?w=500&q=80',
    description: 'Trendy mint green lehenga with a peplum-style embroidered blouse. The lehenga skirt features subtle sequin work and the dupatta is styled as a drape — perfect for sangeet and cocktail parties.',
    features: ['Peplum Blouse','Sequin Skirt','Draped Dupatta','Trendy Silhouette'],
    brand: 'Shyamal & Bhumika', tags: ['trending'], badge: '💚 Trending', discount: 33,
  },
  {
    id: 28, name: 'Gold Tissue Silk Saree', category: 'ethnic', gender: 'women',
    occasion: 'wedding', color: 'Gold', fabric: 'Tissue Silk',
    size: ['Free Size'], pricePerDay: 599, deposit: 2000,
    rating: 4.8, reviewCount: 312, totalRentals: 689, available: true,
    trending: true, celebrity: false,
    image: 'https://images.unsplash.com/photo-1617196034099-e63fd4a09e76?w=500&q=80',
    description: 'Shimmering gold tissue silk saree that catches light from every angle. Fine gold metallic weave creates a luxurious shimmer perfect for weddings and grand celebrations. Includes matching golden blouse.',
    features: ['Tissue Silk','Gold Metallic Weave','All-Over Shimmer','Matching Blouse'],
    brand: 'Nalli Silks', tags: ['trending'], badge: '✨ Golden Hour', discount: 30,
  },
  {
    id: 29, name: 'Floral Maxi Dress', category: 'casual', gender: 'women',
    occasion: 'casual', color: 'Multicolor', fabric: 'Crepe',
    size: ['XS','S','M','L','XL'], pricePerDay: 249, deposit: 800,
    rating: 4.5, reviewCount: 134, totalRentals: 345, available: true,
    trending: false, celebrity: false,
    image: 'https://images.unsplash.com/photo-1572804013427-4d7ca7268217?w=500&q=80',
    description: 'Effortlessly chic multicolor floral print maxi dress in lightweight crepe. V-neckline, flowing silhouette, and puff sleeves — perfect for garden parties, family outings, and Sunday brunches.',
    features: ['Floral Print','V-Neckline','Puff Sleeves','Midi/Maxi Length'],
    brand: 'Zara Inspired', tags: [], badge: null, discount: 18,
  },
  {
    id: 30, name: 'Red Banarasi Silk Saree', category: 'ethnic', gender: 'women',
    occasion: 'wedding', color: 'Red', fabric: 'Banarasi Silk',
    size: ['Free Size'], pricePerDay: 799, deposit: 3000,
    rating: 4.9, reviewCount: 456, totalRentals: 989, available: true,
    trending: true, celebrity: false,
    image: 'https://images.unsplash.com/photo-1610030469983-98e550d6193c?w=500&q=80',
    description: 'Timeless treasure — authentic red Banarasi silk saree with real gold and silver zari weaving in floral and peacock motifs. Rich pallu and contrast border make this non-negotiable for weddings.',
    features: ['Authentic Banarasi','Real Gold Zari','Peacock Motifs','Heavy Pallu'],
    brand: 'Kashi Silk', tags: ['trending','bestseller'], badge: '🏆 #1 Wedding Pick', discount: 40,
  },
  {
    id: 31, name: 'Teal Georgette Gown', category: 'formal', gender: 'women',
    occasion: 'party', color: 'Teal', fabric: 'Georgette',
    size: ['XS','S','M','L'], pricePerDay: 499, deposit: 1800,
    rating: 4.7, reviewCount: 198, totalRentals: 456, available: true,
    trending: false, celebrity: false,
    image: 'https://images.unsplash.com/photo-1550639524-a9625e4de0b8?w=500&q=80',
    description: 'Flowy teal blue georgette gown with ruched detailing at the waist and a romantic one-shoulder neckline. Cascading georgette creates beautiful movement — ideal for cocktail parties.',
    features: ['One Shoulder','Ruched Waist','Flowy Georgette','Knee Length'],
    brand: 'Rina Dhaka', tags: [], badge: null, discount: 22,
  },
  {
    id: 32, name: 'Sage Green Fusion Gown', category: 'ethnic', gender: 'women',
    occasion: 'party', color: 'Sage Green', fabric: 'Silk Organza',
    size: ['S','M','L','XL'], pricePerDay: 649, deposit: 2200,
    rating: 4.8, reviewCount: 223, totalRentals: 512, available: true,
    trending: true, celebrity: false,
    image: 'https://images.unsplash.com/photo-1485968579580-b6d095142e6e?w=500&q=80',
    description: 'Sophisticated sage green Indo-Western gown blending traditional embroidery with a modern silhouette. High-neck collar, embellished yoke, and floor-length flare — contemporary and culturally rooted.',
    features: ['High Neck','Embellished Yoke','Floor Length','Indo-Western Fusion'],
    brand: 'Manish Malhotra', tags: ['trending'], badge: '🌿 Fusion', discount: 32,
  },
  {
    id: 33, name: 'Cobalt Blue Dhoti Kurta', category: 'ethnic', gender: 'men',
    occasion: 'party', color: 'Cobalt Blue', fabric: 'Silk Blend',
    size: ['S','M','L','XL'], pricePerDay: 399, deposit: 1400,
    rating: 4.7, reviewCount: 145, totalRentals: 367, available: true,
    trending: true, celebrity: false,
    image: 'https://images.unsplash.com/photo-1566174053879-31528523f8ae?w=500&q=80',
    description: 'Striking cobalt blue asymmetric kurta with matching dhoti pants in silk blend. Silver block printed motifs along the hem and cuffs add festive flair. Great for mehendi and sangeet.',
    features: ['Asymmetric Hem','Silver Block Print','Dhoti Pants','Silk Blend'],
    brand: 'Sabyasachi Men', tags: ['trending'], badge: '💙 Stand Out', discount: 25,
  },
  {
    id: 34, name: 'White Chikankari Kurti Set', category: 'casual', gender: 'women',
    occasion: 'casual', color: 'White', fabric: 'Georgette',
    size: ['XS','S','M','L','XL','XXL'], pricePerDay: 249, deposit: 800,
    rating: 4.6, reviewCount: 312, totalRentals: 789, available: true,
    trending: false, celebrity: false,
    image: 'https://images.unsplash.com/photo-1583143024015-6c029b9d7c7a?w=500&q=80',
    description: 'Classic white Lucknowi chikankari kurti in soft georgette with intricate hand-done embroidery. Paired with matching palazzo pants — this timeless combo works for casual outings to cultural events.',
    features: ['Hand Chikankari','Lucknowi Craft','Palazzo Included','Versatile'],
    brand: 'Lucknow Chikan', tags: [], badge: '🤍 Timeless', discount: 18,
  },
  {
    id: 35, name: 'Tangerine Phulkari Patiala', category: 'ethnic', gender: 'women',
    occasion: 'festival', color: 'Tangerine Orange', fabric: 'Phulkari Cotton',
    size: ['S','M','L','XL','XXL'], pricePerDay: 299, deposit: 1000,
    rating: 4.6, reviewCount: 167, totalRentals: 423, available: true,
    trending: false, celebrity: false,
    image: 'https://images.unsplash.com/photo-1600080972464-8e5f35f63d08?w=500&q=80',
    description: 'Vibrant tangerine orange phulkari Patiala suit with multicolored embroidery. Voluminous Patiala salwar and matching dupatta with phulkari borders — quintessentially Punjabi for Lohri or Baisakhi.',
    features: ['Phulkari Embroidery','Patiala Salwar','Dupatta Included','Pure Cotton'],
    brand: 'Punjab Handlooms', tags: [], badge: null, discount: 20,
  },
  {
    id: 36, name: 'Olive Green Linen Blazer', category: 'casual', gender: 'men',
    occasion: 'casual', color: 'Olive Green', fabric: 'Linen',
    size: ['S','M','L','XL'], pricePerDay: 299, deposit: 1000,
    rating: 4.5, reviewCount: 89, totalRentals: 234, available: true,
    trending: false, celebrity: false,
    image: 'https://images.unsplash.com/photo-1617196034085-b08de9bff5f0?w=500&q=80',
    description: 'Relaxed yet refined olive green linen blazer — perfect for smart-casual occasions. Unstructured shoulder gives a relaxed Italian look for brunches, beach events, and casual dates.',
    features: ['Unstructured Shoulder','Relaxed Fit','Natural Linen','Breathable'],
    brand: 'Zara Man', tags: [], badge: null, discount: 15,
  },
  {
    id: 37, name: 'Deep Purple Velvet Saree', category: 'ethnic', gender: 'women',
    occasion: 'party', color: 'Deep Purple', fabric: 'Velvet Georgette',
    size: ['Free Size'], pricePerDay: 549, deposit: 1800,
    rating: 4.7, reviewCount: 234, totalRentals: 567, available: true,
    trending: false, celebrity: false,
    image: 'https://images.unsplash.com/photo-1617627143750-d86bc21e42bb?w=500&q=80',
    description: 'Opulent deep purple velvet georgette saree with gold thread embroidery across the body and pallu. Velvet texture gives a rich, premium feel while georgette lining ensures comfort. Includes embroidered blouse.',
    features: ['Velvet Georgette','Gold Embroidery','Embroidered Blouse','Rich Texture'],
    brand: 'Tarun Tahiliani', tags: [], badge: null, discount: 25,
  },
  {
    id: 38, name: 'Yellow Banarasi Lehenga', category: 'ethnic', gender: 'women',
    occasion: 'wedding', color: 'Yellow', fabric: 'Banarasi Silk',
    size: ['XS','S','M','L'], pricePerDay: 799, deposit: 3000,
    rating: 4.9, reviewCount: 345, totalRentals: 789, available: true,
    trending: true, celebrity: false,
    image: 'https://images.unsplash.com/photo-1585771724684-38269d6639fd?w=500&q=80',
    description: 'Radiant yellow Banarasi silk lehenga with intricate gold brocade weaving in peacock and lotus motifs. Heavily embellished choli and dupatta with real zari borders — perfect for haldi or mehendi.',
    features: ['Banarasi Brocade','Real Zari','Peacock Motifs','Heavy Choli','Dupatta'],
    brand: 'Kashi Weaves', tags: ['trending'], badge: '🌼 Haldi Favourite', discount: 38,
  },
  {
    id: 39, name: 'Midnight Blue Double Breasted Suit', category: 'formal', gender: 'men',
    occasion: 'party', color: 'Midnight Blue', fabric: 'Italian Wool',
    size: ['S','M','L','XL'], pricePerDay: 599, deposit: 2000,
    rating: 4.8, reviewCount: 189, totalRentals: 467, available: true,
    trending: true, celebrity: false,
    image: 'https://images.unsplash.com/photo-1521341957697-b93b29c49547?w=500&q=80',
    description: 'Sophisticated midnight blue double-breasted suit in Italian wool with peak lapels and gold buttons. Power silhouette works for formal business events and cocktail parties. Includes matching trousers.',
    features: ['Italian Wool','Double Breasted','Peak Lapels','Gold Buttons'],
    brand: 'Canali India', tags: ['trending'], badge: '👔 Power Dressing', discount: 30,
  },
  {
    id: 40, name: 'Peach Off-Shoulder Gown', category: 'formal', gender: 'women',
    occasion: 'party', color: 'Peach', fabric: 'Chiffon',
    size: ['XS','S','M','L'], pricePerDay: 499, deposit: 1600,
    rating: 4.7, reviewCount: 223, totalRentals: 534, available: true,
    trending: true, celebrity: false,
    image: 'https://images.unsplash.com/photo-1612840394816-d23a24c0e89c?w=500&q=80',
    description: 'Feminine peach off-shoulder gown in dreamy chiffon with a ruffled bodice and full-length flared skirt. Soft pastel hue is perfect for engagement parties, baby showers, and garden weddings.',
    features: ['Off Shoulder','Ruffled Bodice','Full Length','Dreamy Chiffon'],
    brand: 'Ritu Kumar', tags: ['trending'], badge: '🍑 Spring Special', discount: 25,
  },
  {
    id: 41, name: 'Wine Red Kurta Jacket Set', category: 'ethnic', gender: 'men',
    occasion: 'festival', color: 'Wine Red', fabric: 'Jacquard',
    size: ['S','M','L','XL'], pricePerDay: 449, deposit: 1500,
    rating: 4.7, reviewCount: 156, totalRentals: 389, available: true,
    trending: false, celebrity: false,
    image: 'https://images.unsplash.com/photo-1555069519-127aadecd7f9?w=500&q=80',
    description: 'Festive wine red kurta with matching structured jacket in self-woven jacquard fabric. The embossed floral pattern adds texture while the jacket transforms the look. Perfect for Diwali or Dussehra.',
    features: ['Jacquard Fabric','Matching Jacket','Self Embossed','Festive Look'],
    brand: 'Manyavar', tags: [], badge: null, discount: 22,
  },
  {
    id: 42, name: 'Aqua Blue Palazzo Suit', category: 'casual', gender: 'women',
    occasion: 'casual', color: 'Aqua Blue', fabric: 'Chiffon',
    size: ['XS','S','M','L','XL','XXL'], pricePerDay: 229, deposit: 700,
    rating: 4.5, reviewCount: 167, totalRentals: 423, available: true,
    trending: false, celebrity: false,
    image: 'https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?w=500&q=80',
    description: 'Light and airy aqua blue chiffon palazzo suit with a long kameez, wide palazzo pants, and matching dupatta. Butterfly print and soft mint tones — perfect for summer gatherings.',
    features: ['Butterfly Print','Wide Palazzo','Dupatta Included','Summer Ready'],
    brand: 'Global Desi', tags: [], badge: null, discount: 16,
  },
  {
    id: 43, name: 'Rose Pink Bridal Lehenga', category: 'ethnic', gender: 'women',
    occasion: 'wedding', color: 'Rose Pink', fabric: 'Net + Satin',
    size: ['XS','S','M','L'], pricePerDay: 899, deposit: 3500,
    rating: 4.9, reviewCount: 478, totalRentals: 956, available: true,
    trending: true, celebrity: false,
    image: 'https://images.unsplash.com/photo-1595777457583-95e059d581b8?w=500&q=80',
    description: 'Breathtaking rose pink bridal lehenga in net over satin with all-over sequin and kundan embroidery. Backless choli design and dupatta with golden scalloped border — the ultimate bridal statement look.',
    features: ['Kundan Work','Backless Choli','All-Over Sequins','Golden Border','5M Skirt'],
    brand: 'Falguni Shane Peacock', tags: ['trending','bestseller'], badge: '💖 Top Bridal', discount: 45,
  },
  {
    id: 44, name: 'Stone Grey Corporate Blazer', category: 'formal', gender: 'women',
    occasion: 'office', color: 'Stone Grey', fabric: 'Wool Blend',
    size: ['XS','S','M','L','XL'], pricePerDay: 299, deposit: 1000,
    rating: 4.6, reviewCount: 134, totalRentals: 356, available: true,
    trending: false, celebrity: false,
    image: 'https://images.unsplash.com/photo-1604014237800-1c9102c219da?w=500&q=80',
    description: 'Sleek stone grey wool blend blazer with a subtle check pattern and single-button closure. Pair with pencil skirts or tailored trousers for a boardroom-ready look. Perfect for networking events.',
    features: ['Subtle Check Pattern','Single Button','Tailored Fit','Versatile'],
    brand: 'W for Woman', tags: [], badge: null, discount: 18,
  },
  {
    id: 45, name: 'Saffron Kesaria Sherwani', category: 'ethnic', gender: 'men',
    occasion: 'wedding', color: 'Saffron Orange', fabric: 'Art Silk',
    size: ['S','M','L','XL'], pricePerDay: 549, deposit: 2000,
    rating: 4.8, reviewCount: 234, totalRentals: 567, available: true,
    trending: false, celebrity: false,
    image: 'https://images.unsplash.com/photo-1600091166971-7f9faad6c498?w=500&q=80',
    description: 'Vibrant saffron (kesaria) sherwani in art silk with silver threadwork embroidery and a contrasting cream churidar. The auspicious orange tone is perfect for morning/day weddings or engagement ceremonies.',
    features: ['Saffron Kesaria','Silver Threadwork','Cream Churidar','Auspicious'],
    brand: 'Manyavar Classic', tags: [], badge: '🌼 Auspicious', discount: 26,
  },
  {
    id: 46, name: 'Black Sequin Lehenga', category: 'ethnic', gender: 'women',
    occasion: 'party', color: 'Black', fabric: 'Sequin Georgette',
    size: ['XS','S','M','L'], pricePerDay: 749, deposit: 2800,
    rating: 4.8, reviewCount: 289, totalRentals: 634, available: true,
    trending: true, celebrity: false,
    image: 'https://images.unsplash.com/photo-1566479179817-0b61da88e4e4?w=500&q=80',
    description: 'Show-stopping black sequin lehenga with all-over silver and gold sequin embroidery. Halter-neck blouse and high-waist skirt silhouette create a glamorous evening look for cocktail parties and receptions.',
    features: ['All-Over Sequins','Halter Neck Blouse','High Waist','Reception Ready'],
    brand: 'Manish Malhotra', tags: ['trending'], badge: '🌟 Glamour Pick', discount: 35,
  },
  {
    id: 47, name: 'Light Blue Indo-Western Jacket', category: 'ethnic', gender: 'men',
    occasion: 'casual', color: 'Light Blue', fabric: 'Cotton Blend',
    size: ['S','M','L','XL','XXL'], pricePerDay: 279, deposit: 900,
    rating: 4.5, reviewCount: 98, totalRentals: 256, available: true,
    trending: false, celebrity: false,
    image: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=500&q=80',
    description: 'Casual yet stylish light blue Indo-western jacket in cotton blend with mandarin collar and printed motifs. Pair with jeans or chinos for a contemporary desi look for casual parties.',
    features: ['Mandarin Collar','Printed Motifs','Cotton Blend','Casual Indo-Western'],
    brand: 'Fabindia', tags: [], badge: null, discount: 16,
  },
  {
    id: 48, name: 'Coral Pink Gharara Suit', category: 'ethnic', gender: 'women',
    occasion: 'wedding', color: 'Coral Pink', fabric: 'Organza Silk',
    size: ['XS','S','M','L'], pricePerDay: 649, deposit: 2200,
    rating: 4.8, reviewCount: 267, totalRentals: 598, available: true,
    trending: true, celebrity: false,
    image: 'https://images.unsplash.com/photo-1612840394816-d23a24c0e89c?w=500&q=80',
    description: 'Elegant coral pink gharara suit in organza silk with gota patti embroidery throughout. The gharara tiered flare and intricate gold embellishments create a dramatic silhouette — perfect for mehndi and sangeet.',
    features: ['Gota Patti Work','Gharara Silhouette','Organza Silk','Tiered Flare'],
    brand: 'Rimple & Harpreet', tags: ['trending'], badge: '🌺 Sangeet Special', discount: 30,
  },
  {
    id: 49, name: 'Steel Grey Jodhpuri Suit', category: 'ethnic', gender: 'men',
    occasion: 'wedding', color: 'Steel Grey', fabric: 'Wool Blend',
    size: ['S','M','L','XL'], pricePerDay: 599, deposit: 2000,
    rating: 4.8, reviewCount: 198, totalRentals: 489, available: true,
    trending: true, celebrity: false,
    image: 'https://images.unsplash.com/photo-1583743814966-8936f5b7be1a?w=500&q=80',
    description: 'Regal steel grey Jodhpuri suit in premium wool blend. The single-breasted structured jacket with collar closures and slim trousers creates a princely look inspired by Rajasthani royalty.',
    features: ['Jodhpuri Collar','Structured Jacket','Slim Trousers','Royal Style'],
    brand: 'Raghavendra Rathore', tags: ['trending'], badge: '👑 Royal Look', discount: 28,
  },
  {
    id: 50, name: 'Ivory Embroidered Anarkali', category: 'ethnic', gender: 'women',
    occasion: 'festival', color: 'Ivory', fabric: 'Chanderi Silk',
    size: ['XS','S','M','L','XL'], pricePerDay: 449, deposit: 1500,
    rating: 4.7, reviewCount: 234, totalRentals: 567, available: true,
    trending: false, celebrity: false,
    image: 'https://images.unsplash.com/photo-1583391733956-3750e0ff4e8b?w=500&q=80',
    description: 'Classic ivory chanderi silk Anarkali with delicate resham embroidery in floral motifs. Mock neck collar, 3/4 sleeves, and floor-length hem create a graceful traditional silhouette for pujas, Eid, and festive events.',
    features: ['Chanderi Silk','Resham Embroidery','Mock Neck','Floor Length','Dupatta'],
    brand: 'Anita Dongre', tags: [], badge: '🤍 Timeless Classic', discount: 22,
  },
];

export const mockCelebrityLooks = [
  {
    id: 1, celebrity: 'Shah Rukh Khan', movie: 'Pathaan (2023)',
    description: 'Iconic action-hero look — black structured jacket with dark turtleneck. Powerful, modern, unmistakably SRK.',
    image: 'https://images.unsplash.com/photo-1617196034183-421b4040ed20?w=500&q=80',
    products: [6, 17, 19], pricePerDay: 799, totalLooks: 3,
  },
  {
    id: 2, celebrity: 'Shah Rukh Khan', movie: 'Jab Tak Hai Jaan',
    description: 'Military ruggedness meets romance — worn leather jacket, khaki tones, effortless cool.',
    image: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=500&q=80',
    products: [17, 21, 36], pricePerDay: 549, totalLooks: 3,
  },
  {
    id: 3, celebrity: 'Shah Rukh Khan', movie: 'Dilwale Dulhania Le Jayenge',
    description: 'The suit that started a movement — ivory bandhgala with gold detailing, the original Raj look.',
    image: 'https://images.unsplash.com/photo-1621784563330-caee0b138a00?w=500&q=80',
    products: [2, 3, 20], pricePerDay: 649, totalLooks: 3,
  },
];

export const mockOrders = [
  {
    id: 'RWH001', product: mockProducts[0], rentalDays: 3, totalAmount: 2097,
    status: 'delivered', orderDate: '2024-01-15', returnDate: '2024-01-18',
    deliveryAddress: '12 MG Road, Bandra West, Mumbai 400050',
  },
  {
    id: 'RWH002', product: mockProducts[8], rentalDays: 2, totalAmount: 2598,
    status: 'out_for_delivery', orderDate: '2024-01-20', returnDate: '2024-01-22',
    deliveryAddress: '45 Hauz Khas Village, New Delhi 110016',
  },
  {
    id: 'RWH003', product: mockProducts[22], rentalDays: 1, totalAmount: 1249,
    status: 'processing', orderDate: '2024-01-25', returnDate: '2024-01-26',
    deliveryAddress: '78 Indiranagar, Bengaluru 560038',
  },
];

export const mockReviews = [
  { id: 1, user: 'Priya Mehta', avatar: 'P', rating: 5, date: '2024-01-10', verified: true,
    comment: 'Absolutely stunning quality! The sherwani was exactly as shown in photos. Fabric is premium, embroidery is detailed, and it came perfectly pressed. Got so many compliments at my brother wedding. Will definitely rent again!', helpful: 24 },
  { id: 2, user: 'Arjun Sharma', avatar: 'A', rating: 5, date: '2024-01-05', verified: true,
    comment: 'Great experience from start to finish. Easy online booking, timely delivery, and the outfit was in excellent condition. Return pickup was hassle-free and the deposit came back within 3 days.', helpful: 18 },
  { id: 3, user: 'Sneha Kapoor', avatar: 'S', rating: 4, date: '2023-12-28', verified: true,
    comment: 'Wore the lehenga to my cousin reception and everyone thought I bought it! Looks very premium. Only reason for 4 stars is delivery was 2 hours late, but customer care was responsive.', helpful: 12 },
  { id: 4, user: 'Rahul Verma', avatar: 'R', rating: 5, date: '2023-12-15', verified: true,
    comment: 'The Pathaan jacket is unreal — looks exactly like the movie. My wife was shocked I was not paying 50000 for it. Quality is exceptional. ReWearHub has changed how I think about fashion!', helpful: 31 },
  { id: 5, user: 'Ananya Singh', avatar: 'A', rating: 5, date: '2023-12-01', verified: true,
    comment: 'Perfect for my Diwali party! The velvet blazer was immaculate. Free delivery and easy returns make ReWearHub a no-brainer. I have recommended it to all my friends.', helpful: 15 },
];
